### ISSUE TITLE
New Feature: change_window::apply - looking for feedback

### ISSUE THREAD

**Issue by jbcraig** [ipcrm/ipcrm-change_window#3]
With the current functionality you can check the change window and set noop() but it causes everything in that manifests scope to set noop().  I will need to have some profiles under change control and others not under change control.  As as and example, our sudoers file is managed through puppe and waiting a week for a change window to come around seems too much.  I can see a few approaches to solving this, assuming a roles/profiles deploy:
### Manage within the role

This would need a layer between the roles and profiles to contain the profiles that need differing changes.  This is ugly and obfuscates the change window.

```
role_a.pp:
include role_a_cc
include role_a_nocc

role_a_cc.pp:
# use change_window to set noop() as appropriate
include profile_a
include profile_b

role_a_nocc.pp
include profile_c
include profile_d
```
### Manage within profile

In this scenario you would add the change_window check in the profiles that require change control.  The only detractor that I see to this is the requirement for coding standards to enforce change windows and the potential for a large number of profiles doing this lookup (repetitive code).
### Manage with new defined class

This define class would accept and change_window name and an array of classes to keep under change control.  Within the define, it would set noop() if appropriate and then use create_resource to include the list of classes.  This would allow a single manifest to control both managed and unmanaged profiles.

**Define code**

```
define change_windor::apply(
  $name_of_window,
  $array_of_classes,
) {
 # lookup change window definition and set noop() as appropriate
array_of_class.each
  include class
}
```

**Role definition**

```
class role::role_a {
  change_window::apply('mywindow', [ 'profile::profile_a', 'profile::profile_b' ])
  include profile::profile_c
  include profile::profile_d
}
```

The issue is the define would use hiera lookups to retrieve the change window definition.  As this is a component module, the use of hiera for lookups is not recommended.  The beauty is that the role definition remains clean and change windows are presented up-front in a clear fashion.

I lean towards the **define** approach.  Do you think that is something to include in the change_window module?  I have a working version but I haven't got the rspec tests to work (hiera is byting me in the arse).

**Comment by ipcrm** [comment]
I see the PR out there for this... I don't think there is any harm in adding the define.  This will give consumers flexibility to do it themselves(ie via the functions) or using the define you've provided.  I'll merge it shortly.

**Comment by ipcrm** [comment]
I've been thinking about this some more - specifically "As this is a component module, the use of hiera for lookups is not recommended" - and your guilting me into coming up with an alternative :)

What about this: 
[Compare my branch with yours](https://github.com/jbcraig/ipcrm-change_window/compare/feature/change_control...ipcrm:jbcraig/define)

Basically this makes the role definition look like this:

``` puppet
class role::role_a {
  change_window::apply{ hiera('mywindow'), [ 'profile::profile_a', 'profile::profile_b' ]}
  include profile::profile_c
  include profile::profile_d
}
```

Three things:  
- We've moved the hiera lookup back into the our roles/profiles - and while not as pretty it does manage to make it more to 'standards'
- If someone is not using hiera they can still utilize your define (just passing in the array via some other mechanism)
- Your define is virtually unchanged, except that it expects to receive an array as input (with the change_windows)

What do you think?

**Comment by jbcraig** [comment]
I like it, works for me.  I was troubled by the hiera lookup in a component module.  I rationalized it because it doesn't actually manage any resources and performs more like a function.  It still presents a clean coding style and meets my needs.

The other item of note is that I used an "each" iterator, which limits this module to the future parser domain.  I'm not sure how you code that requirement into the metadata.json or if we should think up an alternative to maintain backward compatibility.  For my situation, we are nearly done with our 2015.3 upgrade so my world is the future parser from here on out.

Are you planning to update the README docs with this new implementation or should I?

**Comment by ipcrm** [comment]
I'll update - just wanted to get your thoughts on this before I cleaned it up and made it official.  As for the metadata I'll just update the Puppet versions its compatible with - no worries there.  If people are not just starting out and finding this module they must be working around it in other ways in 3.x; or maybe this will give them good reason to upgrade :)

**Comment by ipcrm** [comment]
New PR #5 was created/merged.

**Comment by ipcrm** [comment]
Tag 0.1.6 was created; new module version published to forge.
